'use client'

import { cn } from '@/lib/utils'
import React, { useRef } from 'react'

interface SeatsProps extends React.HTMLAttributes<HTMLDivElement> {}

const seatRows = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

function Seats({ className, ...props }: SeatsProps) {
    const seats = [
        {
            id: 1,
            status: true,
            rowIndex: 1,
            rowName: 'A',
            order: 1,
            isReserved: false,
        },
        {
            id: 2,
            status: true,
            rowIndex: 2,
            rowName: 'A',
            order: 2,
            isReserved: false,
        },
        {
            id: 3,
            status: true,
            rowIndex: 3,
            rowName: 'A',
            order: 3,
            isReserved: false,
        },
        {
            id: 4,
            status: true,
            rowIndex: 4,
            rowName: 'A',
            order: 4,
            isReserved: false,
        },
        {
            id: 5,
            status: true,
            rowIndex: 5,
            rowName: 'A',
            order: 5,
            isReserved: false,
        },
        {
            id: 6,
            status: true,
            rowIndex: 6,
            rowName: 'A',
            order: 6,
            isReserved: false,
        },
        {
            id: 7,
            status: true,
            rowIndex: 7,
            rowName: 'A',
            order: 7,
            isReserved: false,
        },
        {
            id: 8,
            status: true,
            rowIndex: 8,
            rowName: 'A',
            order: 8,
            isReserved: false,
        },
        {
            id: 9,
            status: true,
            rowIndex: 9,
            rowName: 'A',
            order: 9,
            isReserved: false,
        },
        {
            id: 10,
            status: true,
            rowIndex: 10,
            rowName: 'A',
            order: 10,
            isReserved: false,
        },
        {
            id: 11,
            status: true,
            rowIndex: 1,
            rowName: 'A',
            order: 11,
            isReserved: false,
        },
        {
            id: 12,
            status: true,
            rowIndex: 2,
            rowName: 'B',
            order: 12,
            isReserved: false,
        },
        {
            id: 13,
            status: true,
            rowIndex: 3,
            rowName: 'B',
            order: 13,
            isReserved: false,
        },
        {
            id: 14,
            status: true,
            rowIndex: 4,
            rowName: 'B',
            order: 14,
            isReserved: false,
        },
        {
            id: 15,
            status: true,
            rowIndex: 5,
            rowName: 'B',
            order: 15,
            isReserved: false,
        },
        {
            id: 16,
            status: true,
            rowIndex: 6,
            rowName: 'B',
            order: 16,
            isReserved: false,
        },
        {
            id: 17,
            status: true,
            rowIndex: 7,
            rowName: 'B',
            order: 17,
            isReserved: false,
        },
        {
            id: 18,
            status: true,
            rowIndex: 8,
            rowName: 'B',
            order: 18,
            isReserved: false,
        },
        {
            id: 19,
            status: true,
            rowIndex: 9,
            rowName: 'B',
            order: 19,
            isReserved: false,
        },
        {
            id: 20,
            status: true,
            rowIndex: 10,
            rowName: 'B',
            order: 20,
            isReserved: false,
        },
        {
            id: 21,
            status: true,
            rowIndex: 1,
            rowName: 'B',
            order: 21,
            isReserved: false,
        },
        {
            id: 22,
            status: true,
            rowIndex: 2,
            rowName: 'C',
            order: 22,
            isReserved: false,
        },
        {
            id: 23,
            status: true,
            rowIndex: 3,
            rowName: 'C',
            order: 23,
            isReserved: false,
        },
        {
            id: 24,
            status: true,
            rowIndex: 4,
            rowName: 'C',
            order: 24,
            isReserved: false,
        },
        {
            id: 25,
            status: true,
            rowIndex: 5,
            rowName: 'C',
            order: 25,
            isReserved: false,
        },
        {
            id: 26,
            status: true,
            rowIndex: 6,
            rowName: 'C',
            order: 26,
            isReserved: false,
        },
        {
            id: 27,
            status: true,
            rowIndex: 7,
            rowName: 'C',
            order: 27,
            isReserved: false,
        },
        {
            id: 28,
            status: true,
            rowIndex: 8,
            rowName: 'C',
            order: 28,
            isReserved: false,
        },
        {
            id: 29,
            status: true,
            rowIndex: 9,
            rowName: 'C',
            order: 29,
            isReserved: false,
        },
        {
            id: 30,
            status: true,
            rowIndex: 10,
            rowName: 'C',
            order: 30,
            isReserved: false,
        },
        {
            id: 31,
            status: true,
            rowIndex: 1,
            rowName: 'C',
            order: 31,
            isReserved: false,
        },
        {
            id: 32,
            status: true,
            rowIndex: 2,
            rowName: 'D',
            order: 32,
            isReserved: false,
        },
        {
            id: 33,
            status: true,
            rowIndex: 3,
            rowName: 'D',
            order: 33,
            isReserved: false,
        },
        {
            id: 34,
            status: true,
            rowIndex: 4,
            rowName: 'D',
            order: 34,
            isReserved: false,
        },
        {
            id: 35,
            status: true,
            rowIndex: 5,
            rowName: 'D',
            order: 35,
            isReserved: false,
        },
        {
            id: 36,
            status: true,
            rowIndex: 6,
            rowName: 'D',
            order: 36,
            isReserved: false,
        },
        {
            id: 37,
            status: true,
            rowIndex: 7,
            rowName: 'D',
            order: 37,
            isReserved: false,
        },
        {
            id: 38,
            status: true,
            rowIndex: 8,
            rowName: 'D',
            order: 38,
            isReserved: false,
        },
        {
            id: 39,
            status: true,
            rowIndex: 9,
            rowName: 'D',
            order: 39,
            isReserved: false,
        },
        {
            id: 40,
            status: true,
            rowIndex: 10,
            rowName: 'D',
            order: 40,
            isReserved: false,
        },
        {
            id: 41,
            status: true,
            rowIndex: 1,
            rowName: 'D',
            order: 41,
            isReserved: false,
        },
        {
            id: 42,
            status: true,
            rowIndex: 2,
            rowName: 'E',
            order: 42,
            isReserved: false,
        },
        {
            id: 43,
            status: true,
            rowIndex: 3,
            rowName: 'E',
            order: 43,
            isReserved: false,
        },
        {
            id: 44,
            status: true,
            rowIndex: 4,
            rowName: 'E',
            order: 44,
            isReserved: false,
        },
        {
            id: 45,
            status: true,
            rowIndex: 5,
            rowName: 'E',
            order: 45,
            isReserved: false,
        },
        {
            id: 46,
            status: true,
            rowIndex: 6,
            rowName: 'E',
            order: 46,
            isReserved: false,
        },
        {
            id: 47,
            status: true,
            rowIndex: 7,
            rowName: 'E',
            order: 47,
            isReserved: false,
        },
        {
            id: 48,
            status: true,
            rowIndex: 8,
            rowName: 'E',
            order: 48,
            isReserved: false,
        },
        {
            id: 49,
            status: true,
            rowIndex: 9,
            rowName: 'E',
            order: 49,
            isReserved: false,
        },
        {
            id: 50,
            status: true,
            rowIndex: 10,
            rowName: 'E',
            order: 50,
            isReserved: true,
        },
        {
            id: 51,
            status: true,
            rowIndex: 1,
            rowName: 'E',
            order: 51,
            isReserved: false,
        },
        {
            id: 52,
            status: true,
            rowIndex: 2,
            rowName: 'F',
            order: 52,
            isReserved: false,
        },
        {
            id: 53,
            status: true,
            rowIndex: 3,
            rowName: 'F',
            order: 53,
            isReserved: false,
        },
        {
            id: 54,
            status: true,
            rowIndex: 4,
            rowName: 'F',
            order: 54,
            isReserved: false,
        },
        {
            id: 55,
            status: true,
            rowIndex: 5,
            rowName: 'F',
            order: 55,
            isReserved: false,
        },
        {
            id: 56,
            status: true,
            rowIndex: 6,
            rowName: 'F',
            order: 56,
            isReserved: false,
        },
        {
            id: 57,
            status: true,
            rowIndex: 7,
            rowName: 'F',
            order: 57,
            isReserved: false,
        },
        {
            id: 58,
            status: true,
            rowIndex: 8,
            rowName: 'F',
            order: 58,
            isReserved: false,
        },
        {
            id: 59,
            status: true,
            rowIndex: 9,
            rowName: 'F',
            order: 59,
            isReserved: false,
        },
        {
            id: 60,
            status: true,
            rowIndex: 10,
            rowName: 'F',
            order: 60,
            isReserved: false,
        },
        {
            id: 61,
            status: true,
            rowIndex: 1,
            rowName: 'F',
            order: 61,
            isReserved: false,
        },
        {
            id: 62,
            status: true,
            rowIndex: 2,
            rowName: 'G',
            order: 62,
            isReserved: false,
        },
        {
            id: 63,
            status: true,
            rowIndex: 3,
            rowName: 'G',
            order: 63,
            isReserved: false,
        },
        {
            id: 64,
            status: true,
            rowIndex: 4,
            rowName: 'G',
            order: 64,
            isReserved: false,
        },
        {
            id: 65,
            status: true,
            rowIndex: 5,
            rowName: 'G',
            order: 65,
            isReserved: false,
        },
        {
            id: 66,
            status: true,
            rowIndex: 6,
            rowName: 'G',
            order: 66,
            isReserved: false,
        },
        {
            id: 67,
            status: true,
            rowIndex: 7,
            rowName: 'G',
            order: 67,
            isReserved: false,
        },
        {
            id: 68,
            status: true,
            rowIndex: 8,
            rowName: 'G',
            order: 68,
            isReserved: false,
        },
        {
            id: 69,
            status: true,
            rowIndex: 9,
            rowName: 'G',
            order: 69,
            isReserved: false,
        },
        {
            id: 70,
            status: true,
            rowIndex: 10,
            rowName: 'G',
            order: 70,
            isReserved: false,
        },
        {
            id: 71,
            status: true,
            rowIndex: 1,
            rowName: 'G',
            order: 71,
            isReserved: false,
        },
        {
            id: 72,
            status: true,
            rowIndex: 2,
            rowName: 'H',
            order: 72,
            isReserved: false,
        },
        {
            id: 73,
            status: true,
            rowIndex: 3,
            rowName: 'H',
            order: 73,
            isReserved: false,
        },
        {
            id: 74,
            status: true,
            rowIndex: 4,
            rowName: 'H',
            order: 74,
            isReserved: false,
        },
        {
            id: 75,
            status: true,
            rowIndex: 5,
            rowName: 'H',
            order: 75,
            isReserved: false,
        },
        {
            id: 76,
            status: true,
            rowIndex: 6,
            rowName: 'H',
            order: 76,
            isReserved: false,
        },
        {
            id: 77,
            status: true,
            rowIndex: 7,
            rowName: 'H',
            order: 77,
            isReserved: false,
        },
        {
            id: 78,
            status: true,
            rowIndex: 8,
            rowName: 'H',
            order: 78,
            isReserved: false,
        },
        {
            id: 79,
            status: true,
            rowIndex: 9,
            rowName: 'H',
            order: 79,
            isReserved: false,
        },
        {
            id: 80,
            status: true,
            rowIndex: 10,
            rowName: 'H',
            order: 80,
            isReserved: false,
        },
        {
            id: 81,
            status: true,
            rowIndex: 1,
            rowName: 'H',
            order: 81,
            isReserved: false,
        },
        {
            id: 82,
            status: true,
            rowIndex: 2,
            rowName: 'I',
            order: 82,
            isReserved: false,
        },
        {
            id: 83,
            status: true,
            rowIndex: 3,
            rowName: 'I',
            order: 83,
            isReserved: false,
        },
        {
            id: 84,
            status: true,
            rowIndex: 4,
            rowName: 'I',
            order: 84,
            isReserved: false,
        },
        {
            id: 85,
            status: true,
            rowIndex: 5,
            rowName: 'I',
            order: 85,
            isReserved: false,
        },
        {
            id: 86,
            status: true,
            rowIndex: 6,
            rowName: 'I',
            order: 86,
            isReserved: false,
        },
        {
            id: 87,
            status: true,
            rowIndex: 7,
            rowName: 'I',
            order: 87,
            isReserved: false,
        },
        {
            id: 88,
            status: true,
            rowIndex: 8,
            rowName: 'I',
            order: 88,
            isReserved: false,
        },
        {
            id: 89,
            status: true,
            rowIndex: 9,
            rowName: 'I',
            order: 89,
            isReserved: false,
        },
        {
            id: 90,
            status: true,
            rowIndex: 10,
            rowName: 'I',
            order: 90,
            isReserved: false,
        },
        {
            id: 91,
            status: true,
            rowIndex: 1,
            rowName: 'I',
            order: 91,
            isReserved: false,
        },
        {
            id: 92,
            status: true,
            rowIndex: 2,
            rowName: 'J',
            order: 92,
            isReserved: false,
        },
        {
            id: 93,
            status: true,
            rowIndex: 3,
            rowName: 'J',
            order: 93,
            isReserved: false,
        },
        {
            id: 94,
            status: true,
            rowIndex: 4,
            rowName: 'J',
            order: 94,
            isReserved: false,
        },
        {
            id: 95,
            status: true,
            rowIndex: 5,
            rowName: 'J',
            order: 95,
            isReserved: false,
        },
        {
            id: 96,
            status: true,
            rowIndex: 6,
            rowName: 'J',
            order: 96,
            isReserved: false,
        },
        {
            id: 97,
            status: true,
            rowIndex: 7,
            rowName: 'J',
            order: 97,
            isReserved: false,
        },
        {
            id: 98,
            status: true,
            rowIndex: 8,
            rowName: 'J',
            order: 98,
            isReserved: false,
        },
        {
            id: 99,
            status: true,
            rowIndex: 9,
            rowName: 'J',
            order: 99,
            isReserved: false,
        },
        {
            id: 100,
            status: true,
            rowIndex: 10,
            rowName: 'J',
            order: 100,
            isReserved: false,
        },
    ]

    return (
        <div
            className={cn('grid grid-cols-10 justify-center gap-3', className)}
        >
            {seats.map((seat) => {
                return <Seat {...seat} key={seat.id} />
            })}
        </div>
    )
}

interface SeatProps extends React.HTMLAttributes<HTMLDivElement> {
    id: string
    rowIndex: number
    isReserved: boolean
    rowName: string
    order: number
}

function Seat({
    className,
    rowIndex,
    isReserved,
    order,
    rowName,
    id,
    ...props
}: SeatProps) {
    return (
        <label htmlFor={id}>
            <input
                id={id}
                type="checkbox"
                className="peer hidden"
                disabled={isReserved}
                {...props}
            />
            <div
                className={cn(
                    'flex size-7 cursor-pointer select-none items-center justify-center rounded-sm bg-primary-900 ring-1 ring-inset ring-primary-850 hover:ring-highlight-500 peer-checked:bg-highlight-500 peer-checked:ring-highlight-400 peer-disabled:bg-secondary-900 peer-disabled:text-secondary-850',
                    className
                )}
            >
                {rowName}
                {rowIndex}
            </div>
        </label>
    )
}

export default Seats
